# Generated by Django 3.2.8 on 2022-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_remove_mascotas_fechaactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='titulo',
            field=models.CharField(max_length=40, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
